package com.example.telegrambot.enums;

public enum BotState {
    REGISTERED_USER,
    WAITING_REQUEST_MIDJOURNEY,
    ASK_QUERY_MIDJOURNEY,
    WAITING_ART,
    VALIDATE_ART_FROM_MIDJOURNEY,
    VALIDATED_ART_FROM_MIDJOURNEY,

}
